name: goentity github

on:
  schedule:
    - cron: '0 * * * *'  #every hour
  workflow_dispatch:     #allow to run this workflow manually from git action
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history for all branches and tags

      - name: pull
        run: git pull

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: run maingo
        env:
          TOKEN: ${{ secrets.GoEntity_Github }}
        run: go run main.go

      - name: git status check
        run: git status

      - name: config add commit push
        run: |
          git config user.name "GoEntity"
          git config user.email "goentity13@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push

  deploy:
    needs: update
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup page
        uses: actions/configure-pages@v3

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: deploy
        id: deploy
        uses: actions/deploy-pages@v2
