name: Update Blog

on:
  schedule:
    - cron: '0 * * * *'
    #every hour

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Run script
        run: go run main.go

      - name: Commit and push if it changed
        run: |
          git config user.name "GoEntity"
          git config user.email "goentity13@gmail.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
